# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "New iOS build to the Firebase app distribution"
    lane :qa do
       # build_app(
        #    scheme: "Runner",
        #    archive_path: "./build/Runner.xcarchive",
        #    export_method: "development",
        #    output_directory: "./build/Runner"
        #)
        firebase_app_distribution(
            app: "1:879559078407:ios:bc01f1a9019ccd7dcff0a2",
            testers: "risbonyasse@gmail.com",
            release_notes: "Initial test version of the app",
            firebase_cli_path: "/usr/local/bin/firebase",
            ipa_path: "../build/ios/iphoneos/Payload.ipa"

        )
  end
end
